language: python
sudo: false
python:
- '3.4'
install:
- pip install -r requirements.txt
- pip install coverage
- pip install codecov
after_success:
- codecov
script:
- python -m unittest
- nosetests --with-coverage --cover-package=veralite
- python setup.py install
- python setup.py sdist
notifications:
  slack:
    secure: t1+0lvREwDcrpPwFOwL7BVmhlIyWCfEOVGZw6HupNAa5ILbPc2iJgmOfyXDqY4evxcxzCQMO4LX6P0shEJnkdFuLdS2h+EUYj3MlrzL6+10kl+0fj+etaC9BB5Wjpmanf+qDjMtB0GmMGkaMMfJJ2dtqOA+jyCit3KyzHKxAVkG+1Z8awqeUfkcrqeUJB/OcIrGkaTmxB+7YG3NkNGelg2/1VTUFzSjHbzk695VdCX9FcsvI+Eg9f3qoVJN3JKrvRRcQKtDcmKYnYWe+vFZTR7yXWX5KSV9mTQDoVKVJqapGbAjUndzvQ6NnbApG1pCp3gWb9AGa++dFjFzDpvN6aLOX7+00LxLYKDLZ7FKsiVIDi2+tdFitK3zchCdRAbpKiegK68zFU67pOCwmJftFp1GqFq+c4EmSyzaJ9LeNDGMyrIrl8L3QKy63OUDJAsLy82+kNZWpPzUduVDNNrgcX+0d7tPYhj2Shc4GRJcDdJWSrNwAB/xHxPBXoHIhVNIRKDDbjuZ/2ptZAplGiKt1dPDGoNb2+sTiTvEaedQm0Fco+Q9o3OYJzcz1rRgEv6wd1QDuShKmbmSK2u20mP4WMr3dvdU/AKp8+Iy/zxnPUOuuqZAlDIaObEK6jNdr0qEcVw6+hOOB60GZzDZMR1MVxMb8S94RJb6EEpRqkqgPGJE=
deploy:
- provider: pypi
  user: "$pypi_test_user"
  password: "$pypi_test_pass"
  server: "$pypi_test"
  on:
    branch: develop
    python: '3.4'
- provider: pypi
  user: "$pypi_user"
  password: "$pypi_pass"
  server: "$pypi"
  on:
    branch: master
    python: '3.4'
env:
  global:
  - secure: GWu6SxZX7jlQmPDEqTBsrz5N9774V1NFVIEToQLZOqyf+RR5ctt56Z2Rmfv0ov6f/sRh2ZtCqc9BrnUp0XCbDzP6x1jsHCk4KMwjST5fHTz35zaMAVnuZUCf6CTlmj83tQbmu4tgi7rMYGr7grkfCRp8M4QEvym066QDuvWrHq3amiZsc4hAPCuqtjxHSyc0FVp+aullJIIhJL6SYtWSgcngAH61o+9WByJJ+2krzL+24w9XAz+96iriHzuLqETAgSaItgpWk874xbC1VMLudhfmw9jVdMYc1/Fa+uwLNqHWs1xpu02JKeQdK6r04mKX6bPxtYennSQ4i2dvB0ElcKCxu3EOXrpaChkMMqM+3jDZrL+3ZontsMx5fhtb8ZaNUMII1oEDqPa39z8dKkwUVmcdmTmq14o7HYgILixEWs38Vf/tfxgwLZX4fFWyjtIeAd640vkaJlPhCenN+PyWtE2rMDusBUQ6wdegcUJU+ZxgFsQxuuLy5bwe0al/SNnZyyEz6RBLqAllPHmYmu2uMSLE4MGSY/hPDOvMO9aTCzQuaX0HV8KMCeVzjFDrdiJu23pw8VrkqgGwZXDvRvezSs59vdj8x9vGngg9hW+SZBHTC6GOMcZI92ltPImgwBWSjZNunsteNrI/LUa55vAAF8Dv5C+hWHqLkbBKXooqROM=
  - secure: CQtTSyzjfO6dO3/mwdoZiFyAZVVJO4+sh1p0P3uaIN87PWiXvIpqykn82J4aSiWDGB7BcKDS1pnscevVpIEYfzwihM4HCLXQxcvi0EhFPLtKBWKdDKpTm6Vcd7iEEQUhbaNkr0tTyiD/TByIFP3URHvpJyiF9KY4DXV/+XpbWsy2egxV7bqFw1GrYdmFmTKtgLH+1OHFeR/zraTbWcMB0I+aN4ddQC4tfL5YazMDws74307DOPUNCurpNEAm0RoGjkcwVc98Mrc0uyc/G+h+qom1E6YmUt1djNWWTetxtBJ+RHZ+xIF+K0n+885TnDdZBvP/WcyxIxt7xrg5sGl0Gdl3AyaS8k9GfZh+J8SGHJkmshWfceffOWuKZ5JnLDd9VftbjuAsLLnfByw4mtA4feuCPqwvfmBDxHl+qwI9ytxuWh/KFVXI2C8WpUnBvbREosl5Lgqy6je+aXZljrN/tSot8CCue7z7NUMCORAn3aVuDxwKG97nKVcMltRXwr6hIxJhyIJWl8/HPdFXU2sMJMZaSnfWkVaC4ihWAZuj3WfftNr/fFeV7LCUkks5mvipYGDq9RP4genDarqvKbpDHRUgRI0qx5aH/7MYINSHMwqaYon4g9YeZKK3pY3xX1iVWRrOCUi7s3SLRAWt2J3tUQRCZBvAGknqci0zFum4wSk=
