language: python
sudo: false
python:
- '3.4'
install:
- pip install -r requirements.txt
- pip install coverage
script:
- python -m unittest
- nosetests --with-coverage --cover-package=veralite,device,scene,utils
- python setup.py install
- python setup.py sdist
notifications:
  slack:
    secure: t1+0lvREwDcrpPwFOwL7BVmhlIyWCfEOVGZw6HupNAa5ILbPc2iJgmOfyXDqY4evxcxzCQMO4LX6P0shEJnkdFuLdS2h+EUYj3MlrzL6+10kl+0fj+etaC9BB5Wjpmanf+qDjMtB0GmMGkaMMfJJ2dtqOA+jyCit3KyzHKxAVkG+1Z8awqeUfkcrqeUJB/OcIrGkaTmxB+7YG3NkNGelg2/1VTUFzSjHbzk695VdCX9FcsvI+Eg9f3qoVJN3JKrvRRcQKtDcmKYnYWe+vFZTR7yXWX5KSV9mTQDoVKVJqapGbAjUndzvQ6NnbApG1pCp3gWb9AGa++dFjFzDpvN6aLOX7+00LxLYKDLZ7FKsiVIDi2+tdFitK3zchCdRAbpKiegK68zFU67pOCwmJftFp1GqFq+c4EmSyzaJ9LeNDGMyrIrl8L3QKy63OUDJAsLy82+kNZWpPzUduVDNNrgcX+0d7tPYhj2Shc4GRJcDdJWSrNwAB/xHxPBXoHIhVNIRKDDbjuZ/2ptZAplGiKt1dPDGoNb2+sTiTvEaedQm0Fco+Q9o3OYJzcz1rRgEv6wd1QDuShKmbmSK2u20mP4WMr3dvdU/AKp8+Iy/zxnPUOuuqZAlDIaObEK6jNdr0qEcVw6+hOOB60GZzDZMR1MVxMb8S94RJb6EEpRqkqgPGJE=
deploy:
- provider: pypi
  user: "$pypi_test_user"
  password: "$pypi_test_pass"
  server: "$pypi_test"
  on:
    branch: develop
    python: '3.4'
- provider: pypi
  user: "$pypi_user"
  password: "$pypi_pass"
  server: "$pypi"
  on:
    branch: deploy
    python: '3.4'
env:
  global:
  - secure: AdBbL+CYTsl13uxkgLScVG0FuOhKDREJHDUfCBqgKUMWLbATQzS3xueX9NqYV67AnfO0LnZTWkpQawr2kLFy6bo0mmSmczShXFsXInhXtIH6nyUj5A5ANhIYmtP8Za81UUoaUswKW/3C3hNwkv/P0HxR/15OE/LpK8w135lbqteeGkftQkHN5Jxku8bW5fona/7QetmtOxRN3Tvt2IlZgMsdzo9uEBJn8WN0BrvDAE7pAQZy8agdwoV4+aJ2LFket+1KvqYv4xi7wsTaVSdsHFcPrDoGOEZGTYyAS936QoAcdCNUoy1OK+mMWEYtvhursf7mVAzBOjuQ4mgWqWwWC33l3XH8Rg+RupxALTXN2aOdNoMiZCdBrSVTj57K0xF+9YlgRr+h2XxpiQqgzoCnIGYcfKR/IHbPpSlveyMy+/w1sMfiV7w5jF1IZ3N5CLOV0KX7IXgOfROpEntykl1lIO2gtNlEeIjO2iUvCrgC0kRetvI/KnoQRePNLbmRe0My2crjLkQazBzq6mC8CvP6mf+oZRaApCfpJNkB+adPh/XfsIOwr56X/xWRRAkriLtIsK205GWsDVXNqHRDUfE8L4wzXYrcLjtm146D6S4dq6HsbDUitsoqB/wk0jEAmLl/i7xrczeaQSTCxy5fYFtKxkxTDmm4iGNi5GetwAbFGIU=
  - secure: LI/MXutr6Co9/YUO8aAYRTdOK+Nk0enIwvZezl4Ube81EEhgROymr/b+5TGMA25gSUi/DmKOvTKyTUMDgk31FnLwF0rJIwqMUuOsDJ0N6rW7ICIX1esJhD8PTjyP/RlE5yqfASOP2rDVAoovM9KfTQswzE4yt1HDk0qDNlovOcGdfDaE0t0nHFsq6PhVGgquKkMMNU+TCVmBsTGVgcW2hu1fojMgwjukh6AtS6FYDbcy+OQTGBavKUUCQjixBuAJgyJZNGURqsa1a4lEYbNPAJIAtqbuTaxJh1/16OnmvfD5OMQ0Ml9XdD+tTQBdeerV94pWSLLNzHqIYMXyfFD4Qm1r1ja0g/H+Qi+qFW1E9ImFKSWPvSCyPJwvm2oUkIAU1MW1p994lhZel//A+bx9ySz1Hr3qHKRzTbaxqUG8aVaBLUem5CJnCN4xv1QWJKQjwM4hadA43PAF8EkiEaK0g2DZ4YB/FtenqYYD3TCKgZIitseS3pochUvT6/Rq6j64lj5XwHrmUGDcK9rIAjKxfqnJJwgrURynQ5R3LnXOMphs2L9+VrOMJc4npPMDK4g2p+upm9liSbJWEJG9GwKMxHzDrP0UnBfMr6pCXqDcf0j5dQmREEX3X9uL5pSBtZfX/1ytjHA+hT227EGl3QJmhE20Bpk6lmh2j9pPg3iLULE=
